<option value="Alva">Alva</option>
<option value="Boca Grande">Boca Grande</option>
<option value="Bonita Beach">Bonita Beach</option>
<option value="West Of Us41 South Of Bon">West Of Us41 South Of Bon</option>
<option value="Bonita Bay">Bonita Bay</option>
<option value="Pelican Landing And North">Pelican Landing And North</option>
<option value="North Bonita East Of Us41">North Bonita East Of Us41</option>
<!--option value="East Of Us41 North Of Ter">East Of Us41 North Of Ter</option>
<option value="East Of Us41 South Of Ter">East Of Us41 South Of Ter</option-->
<option value="Spanish Wells">Spanish Wells</option>
<option value="East Of Old 41 South Of S">East Of Old 41 South Of S</option>
<option value="South Of Bonita Beach Roa">South Of Bonita Beach Roa</option>
<option value="Burnt Store">Burnt Store</option>
<option value="Buckingham">Buckingham</option>
<option value="Cape Coral">Cape Coral</option>
<option value="Charlotte County">Charlotte County</option>
<option value="Captiva Island">Captiva Island</option>
<option value="Upper Captiva Island">Upper Captiva Island</option>
<option value="Downtown Fort Myers">Downtown Fort Myers</option>
<option value="Estero">Estero</option>
<option value="The Brooks">The Brooks</option>
<option value="Bodwitch Pointe To Cresce">Bodwitch Pointe To Cresce</option>
<option value="Crescent Street To Gulf B">Crescent Street To Gulf B</option>
<option value="Gulf Beach Road To Avenid">Gulf Beach Road To Avenid</option>
<option value="Avenida Pescadora To S.bd">Avenida Pescadora To S.bd</option>
<option value="S.bdry Of Fairview Isles">S.bdry Of Fairview Isles</option>
<option value="San Carlos Island">San Carlos Island</option>
<option value="Black Island">Black Island</option>
<option value="Fort Myers Area">Fort Myers Area</option>
<option value="North Fort Myers Area">North Fort Myers Area</option>
<option value="Gateway">Gateway</option>
<option value="Glades County">Glades County</option>
<option value="Hendry County">Hendry County</option>
<option value="Central Hendr">Central Hendr</option>
<option value="Northeast Hen">Northeast Hen</option>
<option value="Southern Hend">Southern Hend</option>
<option value="North Lehigh Acres">North Lehigh Acres</option>
<option value="South Lehigh Acres">South Lehigh Acres</option>
<option value="Northwest Lehigh Acres">Northwest Lehigh Acres</option>
<option value="Southwest Lehigh Acres">Southwest Lehigh Acres</option>
<option value="West Lehigh Acres">West Lehigh Acres</option>
<option value="Central Lehigh Acres">Central Lehigh Acres</option>
<option value="Northeast Lehigh Acres">Northeast Lehigh Acres</option>
<option value="Southeast Lehigh Acres">Southeast Lehigh Acres</option>
<option value="Marco Island">Marco Island</option>
<option value="Vanderbilt Beach Area">Vanderbilt Beach Area</option>
<option value="Naples Park Area">Naples Park Area</option>
<option value="Pelican Bay Area">Pelican Bay Area</option>
<option value="Crayton Rd Area">Crayton Rd Area</option>
<option value="Olde Naples Area">Olde Naples Area</option>
<option value="Port Royal">Port Royal</option>
<option value="Royal Harbor">Royal Harbor</option>
<option value="South Naples Area">South Naples Area</option>
<option value="Pine Ridge Area">Pine Ridge Area</option>
<option value="N/o Rattlesnake Hammock">N/o Rattlesnake Hammock</option>
<option value="Lely Area">Lely Area</option>
<option value="Golden Gate City">Golden Gate City</option>
<option value="Corkscrew Area">Corkscrew Area</option>
<option value="East Collier S/o 75">East Collier S/o 75</option>
<option value="Out Of Area">Out Of Area</option>
<option value="Outer Islands">Outer Islands</option>
<option value="Pine Island (north)">Pine Island (north)</option>
<option value="Pine Island (south)">Pine Island (south)</option>
<option value="Matlacha">Matlacha</option>
<option value="Sanibel Island">Sanibel Island</option>